name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --configuration production

      - name: Modify index.html
        run: |
          # Find the path to index.html
          INDEX_HTML_PATH=$(find ./dist -name index.html)
          # Remove 'type="module"' from index.html
          sed -i 's/type="module"//g' "$INDEX_HTML_PATH"
          # Replace <base href="./"> with <base href="/">
          sed -i 's|<base href="./">|<base href="/">|g' "$INDEX_HTML_PATH"

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync

      - name: Copy compiled files to remote server using rsync
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'mkdir -p /home/lehrefs.inf/inf22/inf22187/public-html/'
          sshpass -p "$SSH_PASSWORD" rsync -av --delete ./dist/ $SSH_USER@$SSH_HOST:/home/lehrefs.inf/inf22/inf22187/public-html/
